# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: RSS Manager
version: "1.0.0"
slug: rssmanager
description: Example add-on
url: "https://github.com/lasttry/hassio-rss-manager/tree/main/rssmanager"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
